services:
    postgres:
        container_name: dt-photography-gallery-database
        image: postgres
        environment:
          POSTGRES_USER: DTpostgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dt-postgres_db
        ports:
          - '32772:5432'
        volumes:    
          - dt-postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: dt-photography-gallery-db-manage
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'test@email.com'
            PGADMIN_DEFAULT_PASSWORD: 'test'
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
        ports:
            - 16544:80
        volumes:
            - ./docker/servers.json:/pgadmin4/servers.json
        depends_on:
          - "postgres"
            
volumes:
  dt-postgres-data: